name: flutter_searchbox
description: Flutter Searchbox provides a declarative API to query Elasticsearch / OpenSearch and binds UI widgets with various search query types. Designed for use with ReactiveSearch.io.
version: 4.0.1
homepage: https://github.com/appbaseio/flutter-searchbox

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  searchbase: ^4.0.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
